### PR TITLE
fix wrong mtype in unittable and getscripts

### PR DESCRIPTION
**Pull request by pandaro**
referring to this issues [16](https://github.com/eronoobos/BABAR-The-Shardifant/issues/16)
if all good can be closed for now

### CODE REVIEW

**Comment by pandaro** [comment]
problem:
with this new commit some factory return nan value for factory mtype rating

**Comment by eronoobos** [comment]
guessing that's because of this new mtype you put in, 'chk'

**Comment by pandaro** [comment]
no is caused by have only amp mtype in armsthlxuw and corgantuw, dont pass at all factorymtype calculation and 0/0 is nan

**Comment by eronoobos** [comment]
ohh, i see, chk for chickens

**Pull request merged**
